### ISSUE TITLE
URL link error in /open-source-project 

### ISSUE THREAD

**Issue by ck11a** [Samsung/tizen-docs#175]
[/about/tizen-open-source-overview.md]
GBS command-line tools
Gerrit

[/developping/building.md]
GBS Configuration
perform another build

[/developping/setting-up.md]
GBS Configuration

[/porting/application.md]
MIC image creator

[/porting/connectivity.md]
Tizen Bluetooth architecture
Tizen Wi-FI architecture
http://linuxwireless.org
MTP Initiator
MTP Responder

[/porting/graphics-and-ui.md]
Graphics UI diagram
TBM backend
TDM backend
tdm_backend.h
tdm_log.h
tdm_helper.h
Tdm-test-server results

[/porting/kernel.md]
Setting up the Development Environment
MIC Image Creator
Tizen bootup sequence
Early boot sequence
Tizen platform boot sequence
Tizen file system
Tizen partition layout
Tizen file system hierarchy
Tizen MMC architecture

[/porting/location.md]
Tizen location architecture
Tizen geofence architecture
Tizen Maps API

[/porting/multimedia.md]
Multimedia radio framework
Audio layers
Multimedia player framework
Player plugins
Multimedia codecs
Gst-inspect command
gst-omx structuring
gstomx.conf elements
Video encoder configuration

[/porting/system.md]
File system hierarchy
System framework

[/porting/telephony.md]
Telephony architecture
libtapi components
ibtcore components 
Telephony plugins
Telephony server
Initialization sequence
Request processing sequence
Response processing sequence
Indication processing sequence

[/reference/gbs/gbs-build.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/builddata/xxx-build.conf

[/reference/gbs/gbs-devel.md]
Maintenance Models Supported by GBS

[/reference/gbs/gbs-faq.md]
Setting up Development Environment
Installing Development Tools

[/reference/gbs/gbs-import.md]
Manually Maintained Patches

[/reference/gbs/gbs-maintenance-models.md]
gbs devel

[/reference/gbs/gbs-overview.md]
set up the development environment 
install and upgrade tools

[/reference/mic/mic-customize-image.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min...
http://download.tizen.org/snapshots/trunk/common/latest/repos/base/ia32/packages/repodata/

[/reference/mic/mic-overview.md]
set up the development environment
install and upgrade tools
https://github.com/01org/ **(Link to gbs instead of mic.)**

[/reference/mic/mic-reference.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min...

[/release-notes/tizen-2-1.md]
http://tizen.org/feature/telephony.mms **(The feature name has been changed to http://tizen.org/feature/network.telephony.mms)**
http://tizen.org/feature/telephony.sms.cbs **(The feature name has been changed to http://tizen.org/feature/network.telephony.sms.cbs)**

[/release-notes/tizen-2-2-1.md]
http://tizen.org/feature/screen.size.normal.1080.1980 **(This size has been removed from the Feature List.)**

[/release-notes/tizen-2-3-1.md]
https://developer.tizen.org/downloads/sdk/installing-sdk/prerequisites-tizen-sdk

[/release-notes/tizen-2-3.md]
http://tizen.org/privilege/internet” **(The ” symbol was added at the end of url.)**
http://tizen.org/category/wearable_clock

[/release-notes/tizen-2-4.md]
https://developer.tizen.org/downloads/sdk/installing-sdk/prerequisites-tizen-sdk
Tizen SDK Download page
http://www.w3.org/TR/2014/WD-gamepad-20140225/
http://tizen.org/privilege/keymanager.admin **(This feature is duplicated twice in tizen-2-4.md.)**

[/release-notes/tizen-3-0-m2.md]
How to flash to a device

[/release-notes/tizen-3-0-m3.md]
[http://download.tizen.org/releases/milestone/tizen/3.0.m3/3.0.m3-wearable/tizen-3.0-wearable_20170627.1/images/target-circle/ **(The link is not broken, but "[" was added before the url.)**
How to flash to a device

[/release-notes/tizen-3-0-m4.md]
How to flash to a device

[/release-notes/tizen-3-0-milestones.md]
TV package list 
mobile package list

[/release-notes/tizen-4-0-m1.md]
How to flash to a device

[/release-notes/tizen-4-0-m2.md]
How to flash to a device

[/release-notes/tizen-common-milestones.md]
developer guide

[/tizen-studio/environment.md]
http://download.tizen.org/sdk/tizenstudio/opensrc/ts-cli_3.0.17_ubuntu-64.zip

[/TOC.md]
Installing Development Tools **( This error is due to a directory name typo. -> developping)**
Setting up Development Environment
Cloning Tizen Source Files
Building Packages Locally with GBS
Building All Packages Locally with GBS
Contributing Code to Tizen
Creating Tizen Images with MIC
Flashing an Image to Device
Development Tips

**Comment by journey2w** [comment]
**1. tools was changed to "reference"**

[/about/tizen-open-source-overview.md]
GBS command-line tools => done
Gerrit => done

[/developing/building.md]
GBS Configuration => done
perform another build => done

[/developing/setting-up.md]
GBS Configuration

[/porting/application.md]
MIC image creator

[/porting/connectivity.md]
Tizen Bluetooth architecture
Tizen Wi-FI architecture
http://linuxwireless.org
MTP Initiator
MTP Responder

[/porting/graphics-and-ui.md]
Graphics UI diagram
TBM backend
TDM backend
tdm_backend.h
tdm_log.h
tdm_helper.h
Tdm-test-server results

[/porting/kernel.md]
Setting up the Development Environment
MIC Image Creator
Tizen bootup sequence
Early boot sequence
Tizen platform boot sequence
Tizen file system
Tizen partition layout
Tizen file system hierarchy
Tizen MMC architecture

[/porting/location.md]
Tizen location architecture
Tizen geofence architecture
Tizen Maps API

[/porting/multimedia.md]
Multimedia radio framework
Audio layers
Multimedia player framework
Player plugins
Multimedia codecs
Gst-inspect command
gst-omx structuring
gstomx.conf elements
Video encoder configuration

[/porting/system.md]
File system hierarchy
System framework

[/porting/telephony.md]
Telephony architecture
libtapi components
ibtcore components 
Telephony plugins
Telephony server
Initialization sequence
Request processing sequence
Response processing sequence
Indication processing sequence

[/reference/gbs/gbs-build.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/builddata/xxx-build.conf

[/reference/gbs/gbs-devel.md]
Maintenance Models Supported by GBS

[/reference/gbs/gbs-faq.md]
Setting up Development Environment
Installing Development Tools

[/reference/gbs/gbs-import.md]
Manually Maintained Patches

[/reference/gbs/gbs-maintenance-models.md]
gbs devel

[/reference/gbs/gbs-overview.md]
set up the development environment 
install and upgrade tools

[/reference/mic/mic-customize-image.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min...
http://download.tizen.org/snapshots/trunk/common/latest/repos/base/ia32/packages/repodata/

[/reference/mic/mic-overview.md]
set up the development environment
install and upgrade tools
https://github.com/01org/ **(Link to gbs instead of mic.)**

[/reference/mic/mic-reference.md]
http://download.tizen.org/releases/daily/trunk/ivi/latest/images/ivi-min...

[/release-notes/tizen-2-1.md]
http://tizen.org/feature/telephony.mms **(The feature name has been changed to http://tizen.org/feature/network.telephony.mms)**
http://tizen.org/feature/telephony.sms.cbs **(The feature name has been changed to http://tizen.org/feature/network.telephony.sms.cbs)**

[/release-notes/tizen-2-2-1.md]
http://tizen.org/feature/screen.size.normal.1080.1980 **(This size has been removed from the Feature List.)**

[/release-notes/tizen-2-3-1.md]
https://developer.tizen.org/downloads/sdk/installing-sdk/prerequisites-tizen-sdk

[/release-notes/tizen-2-3.md]
http://tizen.org/privilege/internet” **(The ” symbol was added at the end of url.)**
http://tizen.org/category/wearable_clock

[/release-notes/tizen-2-4.md]
https://developer.tizen.org/downloads/sdk/installing-sdk/prerequisites-tizen-sdk
Tizen SDK Download page
http://www.w3.org/TR/2014/WD-gamepad-20140225/
http://tizen.org/privilege/keymanager.admin **(This feature is duplicated twice in tizen-2-4.md.)**

[/release-notes/tizen-3-0-m2.md]
How to flash to a device

[/release-notes/tizen-3-0-m3.md]
[http://download.tizen.org/releases/milestone/tizen/3.0.m3/3.0.m3-wearable/tizen-3.0-wearable_20170627.1/images/target-circle/ **(The link is not broken, but "[" was added before the url.)**
How to flash to a device

[/release-notes/tizen-3-0-m4.md]
How to flash to a device

[/release-notes/tizen-3-0-milestones.md]
TV package list 
mobile package list

[/release-notes/tizen-4-0-m1.md]
How to flash to a device

[/release-notes/tizen-4-0-m2.md]
How to flash to a device

[/release-notes/tizen-common-milestones.md]
developer guide

[/tizen-studio/environment.md]
http://download.tizen.org/sdk/tizenstudio/opensrc/ts-cli_3.0.17_ubuntu-64.zip

**2. the directory name "developping" was changed to "developing".**

[/TOC.md]
Installing Development Tools **( This error is due to a directory name typo. -> developping)** => done
Setting up Development Environment
Cloning Tizen Source Files
Building Packages Locally with GBS
Building All Packages Locally with GBS
Contributing Code to Tizen
Creating Tizen Images with MIC
Flashing an Image to Device
Development Tips

**Comment by journey2w** [comment]
Fixed PR #181
