### ISSUE TITLE
Reviewed PR #212

### ISSUE THREAD

**Issue by sabeena21** [Samsung/tizen-docs#216]
Hello Catherine,

I am attaching the reviewed file.
The path for the file: https://github.com/Samsung/tizen-docs/files/1806396/message-port.zip

Regards,
Sabeena

**Comment by mijin85cho** [comment]
Hello.

While on discussing about this report, there are some points which looks must be shared.
I listed up the points so please refer them.

- When a review request like #212 is asked, it means it is asking  to check the updated points by the author for the file. It is not asking the check of the file which you have now on your workspace. When you start the review, please fetch the review requested version.

   In #212, the author updated 27 lines, so the focus requested point are that 27 lines of docs/application/dotnet/guides/app-management/message-port.md.

  - Of course total check of the message-port.md itself is important to get the consistency of files. (And somtimes related files, too.)
    But if you are going to check whole files, don't ignore author's modification. Please remember that review request is made by an author, who wants to update the document. You must include author's update when you review the file.

- @annie-samsung , Would you please share how to see the diff tool in your team? It looks like some members are confused with how to see the diff tool, so making an uncorrect review result. 

  - Github displays original file in the left, and updated file on the right. 
  - The red highlight means the sentence/word is deleted by the author, and the green highlight means the sentence/word is added. 
    When a sentence has an update inside it, the github will give light (red or green) highlight for that sentence, and give dark (red or green) highlight at the updated point to emphasize it.
    For example in the https://github.com/Samsung/tizen-docs/pull/212/files#diff-8604864d3b05fd21b68b2338ef386a55R47
       - The original sentence is `private static MessagePort _remotePort;`
       - The author changed `_remotePort` into`_msgPort`.
          - So the Gerrit thinks `_remotePort` is deleted 
         - It highlights it with dark red background in the original file view (left side)
          - And the Gerrit thinks `_msgPort` is deleted 
         - It highlights it with dark green background in the updated file view (right side)

- Please  don't use tabs inside the sample code. Always use spaces in front of each sample code line. The mix of tabs and spaces breaks the code alignment. The attached message-port.md file looks below in firefox.
![image](https://user-images.githubusercontent.com/9958374/37379506-155e4c44-2777-11e8-81d5-4edb6d74931e.png)
    The alignment of { is broken.

- Markdown considers empty lines/spaces as one of the code. So be careful with them.
  - Please insert an empty line if you want to make a line break.
  - The opening and closing of the code block should have same spaces infront of them. Otherwise the view will be broken. The updated message-port.md file by Sabeena looks below in firefox. There are 3 spaces in front of opening code block, and 4 spaces in front of closing code block. So it is considered the closing code is not match with opening code, thus neverending code block is created.
        ![image](https://user-images.githubusercontent.com/9958374/37379630-c4d617d8-2777-11e8-81f4-39e7b63a8e26.png)

- If you made an update, check the result of your update if it is working well before you upload it. Please fix the broken contents and don't upload them. I recommend you to use firefox to check md files.

- Last night, Sabeena and I agreed leaving comments on PR is much easier than opening another issue for the PR review.

Regards
Catherine

**Comment by mijin85cho** [comment]
@annie-samsung Hello, Annie, I listed up some points I recognized while reviewing the Check result from SRI-B. Would you please check and share with your team members?
