### ISSUE TITLE
Pending open issues from PRs 48, 49, and 50 

### ISSUE THREAD

**Issue by l10nbridge** [Samsung/tizen-docs#55]
- docs/open-source-tizen/porting/telephony.md:
  In the "References" section bullet list, only the packages were originally mentioned without specific names. For example:
  Original:
  Telephony daemon
  Our fix from wiki:
  Telephony daemon
  platform/core/telephony/telephony-daemon.git

  Is that OK?
- docs/open-source-tizen/tizen-rt/release-notes/tizen-rt-1-0-m1.md:
  You told us not to change release notes, unles there is a typo. This comment needs clarifications.

  Since the release notes are visible on the site, we think that it is important to keep them up-to-date style-wise, and when we read them through and notice some room for improvement, we edit them. Of course we do not modify the factual content of a release note after the release has been published. But improving the language and making the release note more readable should be acceptable to you.

  Are you now saying that we are not allowed to touch release notes, except to fix a glaring typo?
If you are, does this also apply to general style changes that happen in the library all the time?
For example, when trademarks were missing from certain products and we added and fixed those all over, we also fixed them in the release notes. In the future, would those kind of fixes be forbidden for release notes?

  Before we go back to the original version of these release notes, please clarify what exactly we are allowed to do with release notes in the future.
  And if you say that we are only allowed to touch typos, what exactly do you mean by a typo?
  For example, we fixed "Fully Preemptible" > "Fully-preemptible", because it is a typo for us, since it fixes the way the word has been written. If this is not a typo for you, then we need some further clarifications on what exactly is a typo. Do you mean a situation where a wrong word is used (like when "out" is written "our", causing the meaning of the sentence to break down)?

  Or would it be easiest to just agree that we will never touch a published release note for any reason? At least then we will not make any changes that you feel are undesirable.

  Before we go back to the original version of these release notes, please clarify what exactly we are allowed to do with release notes in the future.

- docs/open-source-tizen/tools/gbs/gbs-chroot.md:
We asked whether it is OK to use  “Examples of command usage:” in all command topics, or whether you just want "Examples:". We did not get an answer yet.

- docs/open-source-tizen/tools/gbs/gbs-devel.md
It would be best to have the synopsis in all the command topics. Could you list the missing ones for us (or tell us where to get them), so we can add them?

- The following topics list a lots of details about things happening in (beginning of) 2017. We’re almost at the end now. Have these things happened?
  - docs/open-source-tizen/tizen-rt/rt-goal.md
  - docs/open-source-tizen/tizen-rt/tizen-rt-overview.md

- About the number of profiles:
  docs\what-is-tizen\overview\tizen.md: This topics says that “Currently, 3 profiles are supported: Mobile, Wearable, TV”
  docs/open-source-tizen/about/tizen-open-source-overview.md: This topic says that “The current Tizen profiles are Tizen IVI (in-vehicle infotainment), Tizen Mobile, Tizen TV, and Tizen Wearable”
  One of these MUST BE WRONG!
  Is this content meant for Tizen 3.0 (in which case the correct “current profile” number is 4, and we need to fixed the first topic), or is this content meant for Tizen 4.0 (in which case the correct “current profile” number is 3, and we need to fixed the latter topic).

- Links leading to a subsection within a topic.
  - If we have a new topic that has not been rendered yet, how do we confirm the header ID?
  - If the links are implemented with IDs that are not included in the MD files, how are we going to run any kind of link checks? Who exactly is going to be responsible for checking that all links within the library work?
  We could have checked the links if they had been implemented as we first thought, with the <a name=”anchor”></a> tags added after the headings. But if that is not allowed, we do not know how to verify that links actually work.
  Please clarify how exactly we can verify that all links work in this system?

- Code blocks
  - What is the correct "language" text to be used for HTML and EDC code examples?
  - If the code snippet shows both a CLI command and the command results, is the correct language code then “bash” or nothing?
  - Some of the files we have received for editing have used "sh" as a language for a code block. Is that OK?

- Superscript
  How is superscript text created?
- Highlight in code blocks
  How do we create a highlight for specific parts of text within a code block? (This was created with a highlight class and span element in HTML…) Or is this not supported anymore?

- Image width limitations
  Since the TOC box has been removed, does it mean that we do not need to worry about images at the top of the topic anymore, and the separate 450 pixel limitation for images next to the TOC box no longer exists? So all images simply need to be at most 850 pixels wide?

- Tables
  - Is any kind of table cell merging allowed anymore? If yes, how should it be implemented?
  - If a table cell requires text with line breaks, we are implementing those with `<br>` . Is that OK?
  - If a table cell requires lists, we are using `<ul>…</ul>` or `<ol>…</ol>`. Is that OK?
  - If a table cell requires a code block, how is that implemented?
  - If a table requires inline code text inside a bullet list, how is that implemented?

- Confusing instructions in the GitHub site:
  - The instructions say that titles should use sentence case (only first letter of first word capitalized). Our current library uses title case (all first letters capitalized). Ha you really changed the title rules for some unknown reason? Do we need to change all the titles in all our topics?
  - What are the rules for using the "horizontal rule" ---?
    We have not used this kind of dividing line before, and cannot think of a reason why to use it in the future. Please clarify exactly in what kind of circumstances it is needed. Otherwise, we will not use it, and will delete it in all the topics we edit.
  - The new writing rules state that italics is supposed to be used for files/folders/paths/new terms.
    In the current documentation, we have avoided italics completely, since it tends to be hard to read from an electronic screen. Currently we are using inline code to write files/folders/paths, and use either quotes and bold font for new terms, as needed.
    Are we now really supposed to follow this new rule and change every single file/folder/path/new term instance to use italics?
  - The new writing rules are confusing, They state that an automatic list of second level heading links will be generated as an "In this article" section at the beginning. However, the template guide still contains a separate "Content" section.
    So what exactly is the plan? Are we supposed to provide some kind of "content" section separately (and add it manually) in all the topics, while the system also generates an automatic "In this article" section? This makes no sense.
    (By the way, we did not know about the automatically generated "In this article" issue, so some of the topics we have already edited now contain a link list at the beginning linking to the subsections (a bit like a "content" section, though not named that way. So based on what the plan here actually is, some changes will be needed in the topics we already edited.)

**Comment by journey2w** [comment]
- docs/open-source-tizen/porting/telephony.md:
  In the "References" section bullet list, only the packages were originally mentioned without specific names. For example:
  Original:
  Telephony daemon
  Our fix from wiki:
  Telephony daemon
  platform/core/telephony/telephony-daemon.git

  Is that OK?
> Engineers can know where it is.
> https://review.tizen.org/gerrit/#/admin/projects/platform/core/telephony/telephony-daemon

- docs/open-source-tizen/tizen-rt/release-notes/tizen-rt-1-0-m1.md:
  You told us not to change release notes, unles there is a typo. This comment needs clarifications.

  Since the release notes are visible on the site, we think that it is important to keep them up-to-date style-wise, and when we read them through and notice some room for improvement, we edit them. Of course we do not modify the factual content of a release note after the release has been published. But improving the language and making the release note more readable should be acceptable to you.

  Are you now saying that we are not allowed to touch release notes, except to fix a glaring typo?
If you are, does this also apply to general style changes that happen in the library all the time?
For example, when trademarks were missing from certain products and we added and fixed those all over, we also fixed them in the release notes. In the future, would those kind of fixes be forbidden for release notes?

  Before we go back to the original version of these release notes, please clarify what exactly we are allowed to do with release notes in the future.

  And if you say that we are only allowed to touch typos, what exactly do you mean by a typo?
  For example, we fixed "Fully Preemptible" > "Fully-preemptible", because it is a typo for us, since it fixes the way the word has been written. If this is not a typo for you, then we need some further clarifications on what exactly is a typo. Do you mean a situation where a wrong word is used (like when "out" is written "our", causing the meaning of the sentence to break down)?
  Or would it be easiest to just agree that we will never touch a published release note for any reason? At least then we will not make any changes that you feel are undesirable.

  Before we go back to the original version of these release notes, please clarify what exactly we are allowed to do with release notes in the future.

> I think you misunderstood me. 
> What is original release notes that you think me? 
> I mean the original release notes is the published release notes after you reviewed it. Moreover, release notes is published after it is approved by someone who confirms the release. 
> The context should not be different from the approved release notes.

> We hope to review and edit the draft of release notes. I always thank you for your works. BTW, when reviewers are changed, the docs are sometimes changed although the meaning of the sentences is correct and readable. I worry about this kinds of reviews. 

> You are an expert.  If you think the sentence is wrong because of typos, wrong words, ugly grammar, and etc, please change any docs.

> A typo is http://www.dictionary.com/browse/typo?s=t. You are right because Preemptible have to write preemptible. I seemed to focus on the just "-" at that time.
> I hope you don't change the published release notes to make a fluent and flowery style.
> When reviewers review commits, they want to share reviewer's opinion. Me too.

- docs/open-source-tizen/tools/gbs/gbs-chroot.md:
We asked whether it is OK to use  “Examples of command usage:” in all command topics, or whether you just want "Examples:". We did not get an answer yet.
> I think "Examples:".

- docs/open-source-tizen/tools/gbs/gbs-devel.md
It would be best to have the synopsis in all the command topics. Could you list the missing ones for us (or tell us where to get them), so we can add them?
> Sure, thank you.

- The following topics list a lots of details about things happening in (beginning of) 2017. We’re almost at the end now. Have these things happened?
  - docs/open-source-tizen/tizen-rt/rt-goal.md
  - docs/open-source-tizen/tizen-rt/tizen-rt-overview.md
> Reviewed by you 20 APRIL, 2017 - 23:17 BY EDITOR LIONBRIDGE. They are almost same the published ones.

- About the number of profiles:
  docs\what-is-tizen\overview\tizen.md: This topics says that “Currently, 3 profiles are supported: Mobile, Wearable, TV”
  docs/open-source-tizen/about/tizen-open-source-overview.md: This topic says that “The current Tizen profiles are Tizen IVI (in-vehicle infotainment), Tizen Mobile, Tizen TV, and Tizen Wearable”
  One of these MUST BE WRONG!
  Is this content meant for Tizen 3.0 (in which case the correct “current profile” number is 4, and we need to fixed the first topic), or is this content meant for Tizen 4.0 (in which case the correct “current profile” number is 3, and we need to fixed the latter topic).
> There are 4 profiles, Mobile, Wearable, TV and IVI.
> Tizen 3.0 supports 4 profiles, but the other versions support 3 profiles except IVI.

- Links leading to a subsection within a topic.
  - If we have a new topic that has not been rendered yet, how do we confirm the header ID?

  - If the links are implemented with IDs that are not included in the MD files, how are we going to run any kind of link checks? Who exactly is going to be responsible for checking that all links within the library work?
> After converting all publisehd docs, we will check all links.

  We could have checked the links if they had been implemented as we first thought, with the <a name=”anchor”></a> tags added after the headings. But if that is not allowed, we do not know how to verify that links actually work.
  Please clarify how exactly we can verify that all links work in this system?
> It works. When the staging server is ready, we can check the links.

- Code blocks
  - What is the correct "language" text to be used for HTML and EDC code examples?
> See README.md.
  - If the code snippet shows both a CLI command and the command results, is the correct language code then “bash” or nothing?
  - Some of the files we have received for editing have used "sh" as a language for a code block. Is that OK?
> Languages for syntax highlighting depend on the markdown plugins installed on the server.
Please keep the base commit at this moment.

- Superscript
  How is superscript text created?
> Markdown doesn't support it.
https://stackoverflow.com/questions/15155778/superscript-in-markdown-github-flavored


- Highlight in code blocks
  How do we create a highlight for specific parts of text within a code block? (This was created with a highlight class and span element in HTML…) Or is this not supported anymore?
> Markdown doesn't support it. When it is need, please use HTML.

- Image width limitations
  Since the TOC box has been removed, does it mean that we do not need to worry about images at the top of the topic anymore, and the separate 450 pixel limitation for images next to the TOC box no longer exists?
> No
 So all images simply need to be at most 850 pixels wide?
> Yes.
>BTW, I think some of queries were already answered.

- Tables
  - Is any kind of table cell merging allowed anymore? If yes, how should it be implemented?
  - If a table cell requires text with line breaks, we are implementing those with `<br>` . Is that OK?
  - If a table cell requires lists, we are using `<ul>…</ul>` or `<ol>…</ol>`. Is that OK?
  - If a table cell requires a code block, how is that implemented?
  - If a table requires inline code text inside a bullet list, how is that implemented?
> When you are sue to use table, please use it with inline HTML tags with <table>.

- Confusing instructions in the GitHub site:
  - The instructions say that titles should use sentence case (only first letter of first word capitalized). Our current library uses title case (all first letters capitalized). Ha you really changed the title rules for some unknown reason? Do we need to change all the titles in all our topics?
> At this moment, please convert html to md. 
> We will change the title as the style guide when all published docs are added into GitHub, before public official open.

  - What are the rules for using the "horizontal rule" ---?
> When a horizontal line is needed, use "--". 
> markdown allows "---" , "----", "-----" and ----------

    We have not used this kind of dividing line before, and cannot think of a reason why to use it in the future. Please clarify exactly in what kind of circumstances it is needed. Otherwise, we will not use it, and will delete it in all the topics we edit.

  - The new writing rules state that italics is supposed to be used for files/folders/paths/new terms.
    In the current documentation, we have avoided italics completely, since it tends to be hard to read from an electronic screen. Currently we are using inline code to write files/folders/paths, and use either quotes and bold font for new terms, as needed.
    Are we now really supposed to follow this new rule and change every single file/folder/path/new term instance to use italics?
> You don't change the published docs.  I think we need it, but wait and see. (TBD)

  - The new writing rules are confusing, They state that an automatic list of second level heading links will be generated as an "In this article" section at the beginning. However, the template guide still contains a separate "Content" section.

    So what exactly is the plan? Are we supposed to provide some kind of "content" section separately (and add it manually) in all the topics, while the system also generates an automatic "In this article" section? This makes no sense.
    (By the way, we did not know about the automatically generated "In this article" issue, so some of the topics we have already edited now contain a link list at the beginning linking to the subsections (a bit like a "content" section, though not named that way. So based on what the plan here actually is, some changes will be needed in the topics we already edited.)

> A "Content" section has to be removed when the docs site is constructed because TOCs wil be automatically generated by the system on RNB. The final docs don't need a "Contents" section or "In this article" section. 
> See http://docs.docker.com.

**Comment by l10nbridge** [comment]
The following issues are still open:


- docs/open-source-tizen/tools/gbs/gbs-devel.md
  It would be best to have the synopsis in all the command topics. Could you list the missing ones for us (or tell us where to get them), so we can add them?

  journey2w: Absolutely, thank you.
  l10nbridge: OK, we will add the synopsis to the devel topic for now, and will add it to the remaining topics if and when you provide the needed details.
  

- The following topics list a lots of details about things happening in (beginning of) 2017. We’re almost at the end now. Have these things happened?
  -  docs/open-source-tizen/tizen-rt/rt-goal.md
  -  docs/open-source-tizen/tizen-rt/tizen-rt-overview.md

   journey2w: Reviewed by you on 20 APRIL, 2017 - 23:17 BY EDITOR LIONBRIDGE. They are almost same the published ones.
  l10nbridge: Those topics contain sentences that state that something is going to happen in 2017, especially in early 2017. That makes no sense, since you need to know by now whether it actually happened or not. At least the following sentences must be fixed. Please let us know whether these things have already happened, or whether they are still something that will be happening at some point later on?
  - The IoT JavaScript Framework (IoT.js) is expected to support ARTIK in the first quarter of 2017 and continue to open source activities to increase the popularity of IoT.js.
  - Per-thread memory protection is expected to be implemented in the first half of 2017.
  - The microkernel architecture is to be designed in the first half of 2017 and the per-thread memory protection implementation is to be followed by microkernel implementation.

- Links leading to a subsection within a topic. 
  This issue is still quite unclear to us. However, we are going to ignore it for now. We will fix the links as best we can, and then we will assume that you can check and fix them somehow before publication. We will NOT take any responsibility for links that may be broken!
However, could you please tell us which Firefox markdown plugin you are using? We are currently using "Markdown Viewer Webext", but it does not support this way of implementing the inline links (it only supports the `<a>` tag linking that we mentioned before). So we are at the moment truly unable to check any inline links created with your approach.

- Code blocks
  What is the correct "language" text to be used for HTML and EDC code examples?

  journey2w: See README.md.
  l10nbridge: The file contains no info about this issue. What exactly are we supposed to look at?

- Superscript:
  Do you mean that we can use `<sup></sup>`?

- Highlight in code blocks

  journey2w: Markdown doesn't support it. When it is need, please use HTML.
  l10nbridge: Can you give an example as to how to implement HTML tagging inside an MD code block?

**Comment by journey2w** [comment]
The following issues are still open:

- docs/open-source-tizen/tools/gbs/gbs-devel.md
  It would be best to have the synopsis in all the command topics. Could you list the missing ones for us (or tell us where to get them), so we can add them?
  journey2w: Absolutely, thank you.
  l10nbridge: OK, we will add the synopsis to the devel topic for now, and will add it to the remaining topics if and when you provide the needed details.



Ok



- The following topics list a lots of details about things happening in (beginning of) 2017. We’re almost at the end now. Have these things happened?
  - docs/open-source-tizen/tizen-rt/rt-goal.md
  - docs/open-source-tizen/tizen-rt/tizen-rt-overview.md
   journey2w: Reviewed by you on 20 APRIL, 2017 - 23:17 BY EDITOR LIONBRIDGE. They are almost same the published ones.
  l10nbridge: Those topics contain sentences that state that something is going to happen in 2017, especially in early 2017. That makes no sense, since you need to know by now whether it actually happened or not. At least the following sentences must be fixed. Please let us know whether these things have already happened, or whether they are still something that will be happening at some point later on?
  - The IoT JavaScript Framework (IoT.js) is expected to support ARTIK in the first quarter of 2017 and continue to open source activities to increase the popularity of IoT.js.
  - Per-thread memory protection is expected to be implemented in the first half of 2017.
  - The microkernel architecture is to be designed in the first half of 2017 and the per-thread memory protection implementation is to be followed by microkernel implementation.
  
  Keep the contents.
  
- Links leading to a subsection within a topic. 
  This issue is still quite unclear to us. However, we are going to ignore it for now. We will fix the links as best we can, and then we will assume that you can check and fix them somehow before publication. We will NOT take any responsibility for links that may be broken!
  However, could you please tell us which Firefox markdown plugin you are using? We are currently using "Markdown Viewer Webext", but it does not support this way of implementing the inline links (it only supports the <a> tag linking that we mentioned before). So we are at the moment truly unable to check any inline links created with your approach.

You can do it when there are doc. I mean when there are no docs because they are not migrated,  you can do it  lator.

Please find out and install markdown plugin.



- Code blocks
  What is the correct "language" text to be used for HTML and EDC code examples?
  journey2w: See README.md.
  l10nbridge: The file contains no info about this issue. What exactly are we supposed to look at?
  
  html is xml.  There is no syntax heightlighting module for edc. It is similar with json but I think "'```" is enough.
  
- Superscript:
  Do you mean that we can use <sup></sup>?
  Any HTML tag for displaying superscript and subscript. The new site doesn't use Drupal so we can use HTML tag without depending on WIZWIG editor provided by Drupal .
  
- Highlight in code blocks
  journey2w: Markdown doesn't support it. When it is need, please use HTML.
  l10nbridge: Can you give an example as to how to implement HTML tagging inside an MD code block?

I mean If you want to insert highlighted code in code blocks, you have to use just HTML like below:

    <code>
      <p style="color:red;"> int a = func(); </p>
    </code>

However, I think we had better not to use highlights for some lines in code block. You can explain emphasis lines or keywords with markdown code(code) tag in paragraph explaining the codes.



 Don't use highlight for some API in code block.

**Comment by journey2w** [comment]
This issue is resolved: #64 

If you have a issue, please open a new issue.
