### ISSUE TITLE
Review docs/open-source-tizen/porting/recovery.md

### ISSUE THREAD

**Issue by journey2w** [Samsung/tizen-docs#80]
Please review https://github.com/Samsung/tizen-docs/pull/77

**Comment by journey2w** [comment]
Dear @steelman,
Please review this PR.

**Comment by l10nbridge** [comment]
Dear @steelman,
Thank you for your comments. We need some further clarifications, please see our answers to your comments (I am not sure whether you received an automatic email about them...).

**Comment by l10nbridge** [comment]
Dear @journey2w,

steelman has provided comments, and approved their implementation. The final content is in https://github.com/l10nbridge/tizen-docs/commit/0c12a643502a32ffcbf287f1652bf066725f11a0#commitcomment-25978651.

Do we now need to create a push request to Samsung master or to the steelman's original change, or can you merge the content directly from our fork?
(As you may remember, we did not originally create the push request to steelman's change, because it showed over 2000 changed files due to the major updates that have been going on in the Samsung  master branch. However, a push request to the Samsung master branch only shows 3 changed files.)

Please let us know if we need to do something to help this change proceed towards merging. :-)

**Comment by journey2w** [comment]
Please send PR.

**Comment by l10nbridge** [comment]
PR sent to steelman's original change.
